databaseChangeLog:
  - changeSet:
      id: insert-security
      author: ali
      changes:
        - sql: |
            insert into authorities (authority)
            values ('FULL'), ('READ');

            insert into roles (role, authority_id)
            values ('ROLE_ADMIN', 1), ('ROLE_USER', 2);

            update users
            set enabled = true,
                role_id = 2;